Now truncating input array if ENDIANESS is unknown
libtom/tomsfastmath pull request #15
Opened 2017-04-12 20:19 UTC by bchauvaux

This fix addresses the case where the input array is longer than the fp_int capacity and ENDIANNESS is not specified... in which case the existing code with overflow fp_int

2017-04-13 09:32 UTC, sjaeckel requested changes

2017-04-13 09:32 UTC, sjaeckel commented on src/bin/fp_read_unsigned_bin.c
> +     if (a->used == 0) {
I don't like this if condition being executed every for-loop iteration

2017-04-13 09:44 UTC, sjaeckel commented
I think we can accept this PR, as this makes the behavior of `fp_read_unsigned_bin()` consistent whether or not the endianness is known.

...but the description needs to be fixed as there could never be an overflow...

2017-04-13 17:47 UTC, bchauvaux commented on src/bin/fp_read_unsigned_bin.c
> +     if (a->used == 0) {
I'm not a fan of condition on every loop but when a->used is incremented on every iteration, the last iteration overruns the a->dp array in fp_mul_2d even when c is truncated properly.

2017-04-15 10:14 UTC, sjaeckel commented
> ...but the description needs to be fixed as there could never be an overflow...

damn, I was wrong, the last iteration would indeed overflow `dp`...

2017-04-18 11:19 UTC, merged

2017-04-18 11:37 UTC, sjaeckel commented
Would this change probably make sense too?

```
@@ -13,7 +13,7 @@
 void fp_mul_2d(fp_int *a, int b, fp_int *c)
 {
    fp_digit carry, carrytmp, shift;
-   int x;
+   int x, limit;
 
    /* copy it */
    fp_copy(a, c);
@@ -28,7 +28,8 @@ void fp_mul_2d(fp_int *a, int b, fp_int *c)
    if (b != 0) {
       carry = 0;   
       shift = DIGIT_BIT - b;
-      for (x = 0; x < c->used; x++) {
+      limit = MIN(c->used, FP_SIZE);
+      for (x = 0; x < limit; x++) {
           carrytmp = c->dp[x] >> shift;
           c->dp[x] = (c->dp[x] << b) + carry;
           carry = carrytmp;
```

2017-04-18 17:41 UTC, bchauvaux commented
Yes it would but this is one of the many location where ->used is ... "used". There are few other locations where ->used is increased without verification.